# Generated by Django 6.0.3 on 2026-03-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_bus_travel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='no_of_seats',
            field=models.BigIntegerField(),
        ),
    ]
